// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZgmNz-tXwVL2j6-z060pbuzyD83SJTus',
    appId: '1:384617932825:web:d344817ca399031b712288',
    messagingSenderId: '384617932825',
    projectId: 'zomet-b1b98',
    authDomain: 'zomet-b1b98.firebaseapp.com',
    storageBucket: 'zomet-b1b98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_Fy_4rbtymyWvaF3lyexZF1QwgjZqHs',
    appId: '1:384617932825:android:af6eb43d97234c68712288',
    messagingSenderId: '384617932825',
    projectId: 'zomet-b1b98',
    storageBucket: 'zomet-b1b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJIyoNW_LuMFC7eLOl8y4Cu5E6vLVKcU',
    appId: '1:384617932825:ios:1a030b57eb8a239c712288',
    messagingSenderId: '384617932825',
    projectId: 'zomet-b1b98',
    storageBucket: 'zomet-b1b98.appspot.com',
    iosClientId: '384617932825-333de0pmmrff08s8pfink4tn1d3c9e02.apps.googleusercontent.com',
    iosBundleId: 'com.example.zomet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJIyoNW_LuMFC7eLOl8y4Cu5E6vLVKcU',
    appId: '1:384617932825:ios:1a030b57eb8a239c712288',
    messagingSenderId: '384617932825',
    projectId: 'zomet-b1b98',
    storageBucket: 'zomet-b1b98.appspot.com',
    iosClientId: '384617932825-333de0pmmrff08s8pfink4tn1d3c9e02.apps.googleusercontent.com',
    iosBundleId: 'com.example.zomet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZgmNz-tXwVL2j6-z060pbuzyD83SJTus',
    appId: '1:384617932825:web:4fbba23dfa8939c5712288',
    messagingSenderId: '384617932825',
    projectId: 'zomet-b1b98',
    authDomain: 'zomet-b1b98.firebaseapp.com',
    storageBucket: 'zomet-b1b98.appspot.com',
  );
}
